name: Carga Env Vars

on: 
  workflow_dispatch:
  
env:
  PROFILE: 'ubuntu-latest'
jobs:
  mvn-build:
    name: Maven build
    runs-on: almmc_redhat_runner
    steps:
      - name: Set env
        run: test_var="test"
        shell: bash
      - name: Test bash
        run: echo "$test_var"
        shell: bash
        
