name: Carga Env Vars

on: 
  workflow_dispatch:

jobs:
  env-vars:
    name: Vars
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set env
        shell: bash
        run: |
          test_var="test"
          echo "TAG_VERSION=$test_var" >> $GITHUB_ENV
      - name: Test bash
        shell: bash
        run: echo "$TAG_VERSION"
